version: '3.8'

services:
    nginx:
      build:
        context: docker/nginx
        dockerfile: Dockerfile
      volumes:
        - ./:/app
      ports:
        - "80:80"

    php-fpm:
      build:
        context: docker/php-fpm
        dockerfile: Dockerfile
      volumes:
        - ./:/app
       ## - ./docker/php-configuration:/usr/local/etc/php
      environment:
        DB_HOST: postgresql
        DB_USER: app
        DB_PASSWORD: password
        DB_NAME: app

    php-cli:
      build:
        context: docker/php-cli
        dockerfile: Dockerfile
      volumes:
        - ./:/app
        ##- ./docker/php-configuration:/usr/local/etc/php
      environment:
        DB_HOST: postgresql
        DB_USER:  app
        DB_PASSWORD:  password
        DB_NAME: app

    postgresql:
      image: postgres:16-alpine3.18
      environment:
        DB_HOST: postgresql
        DB_USER: app
        DB_PASSWORD: password
        DB_NAME: app
      volumes:
        - ./docker/postgresql:/var/lib/postgresql/data
      ports:
        - "5432:5432"



